openapi: 3.0.3
info:
  title: Frontend Auth API Schema (Draft)
  version: 1.0.0
  description: Draft schema for frontend integration of auth endpoints.
paths:
  /api/auth/register/:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 150
                password:
                  type: string
                  minLength: 6
                  maxLength: 128
              required: [username, password]
      responses:
        '201':
          description: User registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
                required: [user, token]
        '400':
          description: Validation error
  /api/auth/login/:
    post:
      summary: Login with username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
                required: [user, token]
        '400':
          description: Invalid credentials
  /api/auth/me/:
    get:
      summary: Get current authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        date_joined:
          type: string
          format: date-time
      required: [id, username, date_joined]
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
